# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'not rich' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftChart'
  pod 'EFCountingLabel', '~> 4.0'

  # Pods for not rich

  target 'not richTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'not richUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
